name: Deployement du binaire windows
on: 
  push:
    branches:
      - master 
 
jobs:
  windows:
    runs-on: windows-latest

    strategy:
      matrix:
        architecture: ['x64', 'x86']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: ${{matrix.architecture}}
      - name: install windows deps 
        run: |
            pip install pywin32
            pip install PyInstaller==4.0
            pip install pytest
      - name: test
        run: python -m pytest tests

      - name: create binary 
        run: pyinstaller --name="cuteseq_${{matrix.architecture}}" --hidden-import json --add-data "cuteseq;cuteseq" cuteseq\__main__.py

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: cuteseq-standalone-${{matrix.architecture}}
          path: dist


